spring.application.name=cloud

app.s3.bucket=bucket-jbrr
app.s3.region=us-east-2

app.dynamodb.table-name=image_likes

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.cloud.app.model
mybatis.configuration.map-underscore-to-camel-case=true